routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/socio');
});
Route::get('associacao/{id}/{socioId}', 'SocioController@deleteAssociacao');
Route::get('clube/search/', 'ClubeController@search');  

Auth::routes();
Route::resource('socio', 'SocioController');
Route::resource('clube', 'ClubeController');

app/Socio.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Socio extends Model
{

	public function associacao()
	{
		return $this->hasOne('App\Socio');
	}
}

app/Http/Controllers/SocioController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Support\Facades\DB;
use Illuminate\Http\Request;
use App\Clube;
use App\Socio;
use App\Associacao;

class SocioController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
   
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       $registros = Socio::all();
       $clubes = Db::table('associacaos')->join('clubes', 'clubes.id', '=', 'associacaos.clube_id')->get();
 
       return view('socio.list',['registros' => $registros], ['clubes' => $clubes]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
       $socios = Socio::all();
       return view('socio.create', ['socios' => $socios]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {       
       $this->validate($request,['nome'=> 'required',]);
       
       $registro = new Socio;
       $registro->nome = $request->nome;
       
       $registro->save();
       return redirect()->route('socio.index')->with('alert-success','Registro salvo com sucesso!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function deleteAssociacao($id, $socioId)
    {
      $registro = Associacao::findOrFail($id);
      $registro->delete();
      return redirect()->back()->with('alert-success','Registro excluído com sucesso!');        
        return $test;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
       $registro = Socio::findOrFail($id);
       $clubes = Clube::all();
       $associacoes = Associacao::select('associacaos.id', 'associacaos.clube_id', 'associacaos.socio_id', 'clubes.nome')->where('associacaos.socio_id', '=',$id)->join('clubes', 'clubes.id', '=', 'associacaos.clube_id')->get();
       return view('socio.edit',['registro' => $registro, 'clubes' =>$clubes, 'associacoes' =>$associacoes]);
 }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
       $this->validate($request,['nome'=> 'required','novoClubeId']);
       
       $registro = Socio::findOrFail($id);
       
       $registro->nome = $request->nome;
       $registro->save();
       if($request->novoClubeId) {

          if(Associacao::where([
             ['associacaos.socio_id', '=',$id],
             [ 'associacaos.clube_id', '=', $request->novoClubeId]
             ])->doesntExist()
          ) {
      $associacao = new Associacao;
      $associacao->clube_id = $request->novoClubeId;
      $associacao->socio_id = $id;
      $associacao->save();
      }
      }
      
       return redirect()->route('socio.index')->with('alert-success','Registro salvo com sucesso!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $registro = Socio::findOrFail($id);
        $registro->delete();
        return redirect()->back()->with('alert-success','Registro excluído com sucesso!');
    }  
}

resources/views/socio/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Novo Sócio</div>

                <div class="panel-body">
                    
                   <form role="form" action="{{route('socio.store')}}" method="post">
                     <div class="box-body">
                        {{csrf_field()}}

                        <div class="form-group col-sm-8">
                           <label for="nome">Nome</label>
                           <input type="text" class="form-control" name="nome" placeholder="Informe o nome do Sócio" required>
                        </div>
                         <!-- /.input group -->
                     </div>
                     <!-- /.box-body -->

                    <div class="box-footer">
                      <button type="submit" class="btn btn-primary">Salvar</button>
                       <a href="{{route('socio.index')}}" class="btn btn-default pull-right">Cancelar</a>
                    </div>
                  </form>
                   
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/socio/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading">Edição de Sócio</div><br>

                <div class="panel-body">
                <form role="form" action="{{route('socio.update', $registro->id)}}" method="post">
                     <div class="box-body">
                  <input name="_method" type="hidden" value="PATCH">
                        {{csrf_field()}}

                        <div class="form-group col-sm-8">
                           <label for="nome">Nome</label>
                           <input type="text" class="form-control" name="nome" placeholder="Informe o nome da empresa" value="{{$registro->nome}}" required>
                        </div>
                        <div class="form-group col-sm-8">
                         <label for="novoClubeId">
                            Adicionar Clube:
                            </label>
                            <select class="custom-select mr-sm-1" name="novoClubeId">
                            <option value="" disabled selected></option>
                            @foreach($clubes as $clube)     
                            <option value="{{$clube->id}}">
                            {{$clube->nome}}    
                            </option>
                            @endforeach                        
                          </select>
                         </div>
                         <!-- /.input group -->
                     </div>
                     <!-- /.box-body -->

                    <div class="box-footer">
                      <button type="submit" class="btn btn-primary">Salvar</button>
                       <a href="{{route('socio.index')}}" class="btn btn-default pull-right">Cancelar</a>
                    </div>
                  </form>
               <br><br>
                </div>   
                </div>
                </div>      
            <div class="col-lg-6">
            <div class="panel panel-default">
            <div class="panel-heading">Clubes associados</div><br>
            <div class="panel-body">
        <div class="box-body row ml-3">
        @foreach($associacoes  as $associacao)
        <div>
                <a href="../../associacao/{{$associacao->id}}/{{$associacao->socio_id}}" class="badge badge-danger mr-2" style="float:right">x</a>

        <button id="disabled" disabled href="" class="btn btn-success btn-sm mb-2" style="background-color: #38c172; opacity: 100; ">{{$associacao->nome}} 
        </button>
        </div>
        @endforeach
        </div>
        </div>
        </div>
    </div>  
        </div>
     
</div>
@endsection

resources/views/socio/list.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Sócios  </div>

                <div class="panel-body">
                  <table class="table table-hover">
                  <thead>
                     <tr>
                        <th>Nome</th>
                        <th>Clubes</th>

                     </tr>
                  </thead>
                  <tbody>
                     @foreach($registros as $registro)
                     <td>{{$registro->nome}}</td>
                     <td>
                     @foreach($clubes as $clube)
                     @if($registro->id==$clube->socio_id)
                   <li>  {{$clube->nome}} </li>
                     @endif   
                     @endforeach
                   </td>
                     <td>                   
                           <form class="" action="{{route('socio.destroy',$registro->id)}}" method="post">
                              <input type="hidden" name="_method" value="delete">
                              
                              <input type="hidden" name="_token" value="{{ csrf_token() }}">
                              <a href="{{route('socio.edit',$registro->id)}}" class="btn btn-primary btn-sm">Editar</a>
                              
                              <input type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Você tem certeza que deseja excluir este registro?');" name="name" value="Excluir">
                           </form>
                        </td>
                      
                     </tr>
                     @endforeach
                     </td>
                  </tbody>
                  <tfoot>
                  </tfoot>
               </table>
               <a href="{{route('socio.create')}}" class="btn btn-primary">Novo Sócio</a>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection