routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/socio');
});
Route::get('associacao/{id}/{socioId}', 'SocioController@deleteAssociacao');
Route::get('clube/search/', 'ClubeController@search');  

Auth::routes();
Route::resource('socio', 'SocioController');
Route::resource('clube', 'ClubeController');

app/Clube.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Clube extends Model
{
    public function associacao()
	{
		return $this->hasOne('App\Clube');
	}
}

app/Http/Controllers/ClubeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Clube;
use App\Socio;

class ClubeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
   
    /**
     * @param  \Illuminate\Http\Request  $request
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
      echo($request->content);
      $registros = Clube::all();
       return view('clube.list',['registros' => $registros]);
    }
        /**
     * @param  \Illuminate\Http\Request  $request
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function search(Request $request)
    {
      echo($request->content);
      $registros = Clube::where('nome','like',$request->search.'%')->get();
       return view('clube.list',['registros' => $registros]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
       $socios = Socio::all();
       return view('clube.create', ['socios' => $socios]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {       
       $this->validate($request,['nome'=> 'required',]);
       
       $registro = new Clube;
       $registro->nome = $request->nome;
       
       $registro->save();
       return redirect()->route('clube.index')->with('alert-success','Registro salvo com sucesso!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
       $registro = Clube::findOrFail($id);
       return view('clube.edit',['registro' => $registro]);
 }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
       $this->validate($request,['nome'=> 'required',]);
       
       $registro = Clube::findOrFail($id);
       
       $registro->nome = $request->nome;
       $registro->save();
       
       return redirect()->route('clube.index')->with('alert-success','Registro salvo com sucesso!');
    }

  /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function delete(Request $request, $id)
    {
       
       $registro = Associacao::findOrFail($id);
       $registro->delete();
       
       return redirect()->route('clube.index')->with('alert-success','Registro salvo com sucesso!');
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $registro = Clube::findOrFail($id);
        $registro->delete();
        return redirect()->back()->with('alert-success','Registro excluído com sucesso!');
    }
}

resources/views/clube/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Novo Clube</div>

                <div class="panel-body">
                    
                   <form role="form" action="{{route('clube.store')}}" method="post">
                     <div class="box-body">
                        {{csrf_field()}}

                        <div class="form-group col-sm-8">
                           <label for="nome">Nome</label>
                           <input type="text" class="form-control" name="nome" placeholder="Informe o nome do clube" required>
                        </div>
                         <!-- /.input group -->
                     </div>
                     <!-- /.box-body -->

                    <div class="box-footer">
                      <button type="submit" class="btn btn-primary">Salvar</button>
                       <a href="{{route('clube.index')}}" class="btn btn-default pull-right">Cancelar</a>
                    </div>
                  </form>
                   
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/clube/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Edição do clube</div>

                <div class="panel-body">
                    
                   <form role="form" action="{{route('clube.update', $registro->id)}}" method="post">
                     <div class="box-body">
                  <input name="_method" type="hidden" value="PATCH">
                        {{csrf_field()}}

                        <div class="form-group col-sm-8">
                           <label for="nome">Nome</label>
                           <input type="text" class="form-control" name="nome" placeholder="Informe o nome da empresa" value="{{$registro->nome}}" required>
                        </div>
                         <!-- /.input group -->
                     </div>
                     <!-- /.box-body -->

                    <div class="box-footer">
                      <button type="submit" class="btn btn-primary">Salvar</button>
                       <a href="{{route('clube.index')}}" class="btn btn-default pull-right">Cancelar</a>
                    </div>
                  </form>
                   
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/clube/list.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Clubes  </div>
                <div class="panel-body">
                   <form method="GET" action="{{url('clube/search')}}">
                   <div class="row">
                  <div class="col-sm-12">
                  <input type="hidden" name="_token" value="{{ csrf_token() }}">
                  <input type="hidden" name="_method" value="get">

                   <input name="search" type="text" class="">
                   <button type="submit" name="name" class="btn btn-primary btn-sm">Buscar</button>
                   </div>
               </div>
               </form>
                  <table class="table table-hover">
                  <thead>
                     <tr>
                        <th>Nome</th>
                     </tr>
                  </thead>
                  <tbody>
               

                     @foreach($registros as $registro)
                     <td>{{$registro->nome}}</td>
                     <td>                   
                           <form class="" action="{{route('clube.destroy',$registro->id)}}" method="post">
                              <input type="hidden" name="_method" value="delete">
                              
                              <input type="hidden" name="_token" value="{{ csrf_token() }}">
                              <a href="{{route('clube.edit',$registro->id)}}" class="btn btn-primary btn-sm">Editar</a>
                              
                              <input type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Você tem certeza que deseja excluir este registro?');" name="name" value="Excluir">
                           </form>
                        </td>
                     </tr>
                     @endforeach
                     </td>
                  </tbody>
                  <tfoot>
                  </tfoot>
               </table>
               <a href="{{route('clube.create')}}" class="btn btn-primary">Novo Clube</a>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection